name: Documentation Issue
description: Report missing, incorrect, or unclear documentation.
title: "Docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the docs. Please point us to the exact page or section.
  - type: input
    id: location
    attributes:
      label: Docs location
      description: Link to the page or file path (e.g., `site/docs/...`).
      placeholder: https://github.com/withfabric/spandex/...
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue description
      description: What's wrong or missing?
      placeholder: The example for `createConfig` uses an outdated option...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix
      description: What should we change or add?
    validations:
      required: false
