/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPrepareSimulatedQuotesRouteImport } from './routes/api/prepareSimulatedQuotes'
import { Route as ApiPrepareQuotesRouteImport } from './routes/api/prepareQuotes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrepareSimulatedQuotesRoute =
  ApiPrepareSimulatedQuotesRouteImport.update({
    id: '/api/prepareSimulatedQuotes',
    path: '/api/prepareSimulatedQuotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrepareQuotesRoute = ApiPrepareQuotesRouteImport.update({
  id: '/api/prepareQuotes',
  path: '/api/prepareQuotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/prepareQuotes': typeof ApiPrepareQuotesRoute
  '/api/prepareSimulatedQuotes': typeof ApiPrepareSimulatedQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/prepareQuotes': typeof ApiPrepareQuotesRoute
  '/api/prepareSimulatedQuotes': typeof ApiPrepareSimulatedQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/prepareQuotes': typeof ApiPrepareQuotesRoute
  '/api/prepareSimulatedQuotes': typeof ApiPrepareSimulatedQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/prepareQuotes' | '/api/prepareSimulatedQuotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/prepareQuotes' | '/api/prepareSimulatedQuotes'
  id: '__root__' | '/' | '/api/prepareQuotes' | '/api/prepareSimulatedQuotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPrepareQuotesRoute: typeof ApiPrepareQuotesRoute
  ApiPrepareSimulatedQuotesRoute: typeof ApiPrepareSimulatedQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prepareSimulatedQuotes': {
      id: '/api/prepareSimulatedQuotes'
      path: '/api/prepareSimulatedQuotes'
      fullPath: '/api/prepareSimulatedQuotes'
      preLoaderRoute: typeof ApiPrepareSimulatedQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prepareQuotes': {
      id: '/api/prepareQuotes'
      path: '/api/prepareQuotes'
      fullPath: '/api/prepareQuotes'
      preLoaderRoute: typeof ApiPrepareQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPrepareQuotesRoute: ApiPrepareQuotesRoute,
  ApiPrepareSimulatedQuotesRoute: ApiPrepareSimulatedQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
